spring:
  datasource:
#    url: jdbc:mysql://google/timecloud_alpha?cloudSqlInstance=cloudsql-my:us-central1:gogisttest&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: me
    password: me
    driverClassName: com.mysql.jdbc.Driver
    continue-on-error: true
  # Enforces database initialization
    initialization-mode: always

  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:
    gcp:
      sql:
        database-name: timecloud_alpha
        instance-connection-name: cloudsql-my:us-central1:gogisttest

#logging.level.org.springframework.web=DEBUG
logging:
  level:
    org:
      springframework:
        web: DEBUG
